
  services:

    mysql:
      image: mysql:8.0
      container_name: skillswap-mysql

      environment:
        MYSQL_ROOT_PASSWORD: Samira12
        MYSQL_DATABASE: skillswap_db

      ports:
        - "3310:3306"

      volumes:
        - skillswap-db-data:/var/lib/mysql

      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pSamira12"]
        interval: 5s
        timeout: 5s
        retries: 10

      networks:
        - skillswap-network


    app:
      build: .
      container_name: skillswap-app

      depends_on:
        mysql:
          condition: service_healthy

      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/skillswap_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: Samira12

      ports:
        - "8080:8080"

      networks:
        - skillswap-network


    frontend:
      build: ../skillswap_frontend
      container_name: skillswap-frontend

      depends_on:
        - app

      ports:
        - "5173:5173"

      networks:
        - skillswap-network


  volumes:
    skillswap-db-data:


  networks:
    skillswap-network:

